### ISSUE TITLE
Add instructions for local development to the README

### ISSUE THREAD

**Issue by meshy** [PyconUK/2017.pyconuk.org#13]
I tried the following steps to get the project running:

```bash
# Create a virtualenv:
mkvirtualenv 2017.pyconuk.org -p `which python3`

# Install python requirements:
pip install -r requirements.txt

# Run migrations:
./manage.py migrate

# Run the site:
make serve
```

That gets the server running, but when I browse to http://127.0.0.1:8000/ I get a `500`.

On the presumption that the issue was `ALLOWED_HOSTS`, I tried to run in `DEBUG` mode (`DEBUG=1 make serve`) but then I get the following error:

```pytb
Traceback (most recent call last):
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/base.py", line 260, in precompile
    mod = import_module(mod_name)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'lessc {infile} {outfile}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/charlie/code/pyconuk/2017.pyconuk.org/pyconuk/views.py", line 26, in page
    return render(request, template, context)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/templatetags/compress.py", line 103, in render_compressed
    rendered_output = compressor.output(mode, forced=forced)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/css.py", line 49, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/css.py", line 51, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/base.py", line 292, in output
    output = '\n'.join(self.filter_input(forced))
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/base.py", line 232, in filter_input
    for hunk in self.hunks(forced):
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/base.py", line 204, in hunks
    precompiled, value = self.precompile(value, **options)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/base.py", line 265, in precompile
    return True, filter.input(**kwargs)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/filters/base.py", line 229, in input
    return super(CachedCompilerFilter, self).input(**kwargs)
  File "/home/charlie/venvs/2017.pyconuk.org/lib/python3.6/site-packages/compressor/filters/base.py", line 196, in input
    raise FilterError(err)
compressor.exceptions.FilterError: /bin/sh: lessc: command not found
```

Could there be a missing requirement?

**Comment by Lukasa** [comment]
There is, but it's a javascript one.

`npm install -g less` will resolve your problem.

**Comment by meshy** [comment]
Aha! Thank you.
